<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Destiananda Suksesa Pratiwi">
<meta name="dcterms.date" content="2024-01-16">

<title>Pengaruh Kontribusi Sektor Pertambangan dan Penggalian terhadap Pertumbuhan Ekonomi Provinsi Papua Tahun 2012-2021</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Kontribusi Sektor Pertambangan dan Penggalian terhadap Pertumbuhan Ekonomi Provinsi Papua Tahun 2012-2021</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Destiananda Suksesa Pratiwi </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Pertumbuhan ekonomi adalah peningkatan nilai dan jumlah barang atau jasa yang diproduksi dalam kurun waktu tertentu. Joko Untoro dalam buku Ekonomi Makro (2010) mendefinisikan pertumbuhan ekonomi sebagai perkembangan kegiatan dalam perekonomian yang menyebabkan barang dan jasa yang diproduksi dalam masyarakat bisa bertambah dan kemakmuran akan meningkat dalam jangka panjang. Pertumbuhan ekonomi merupakan indikator dari sebuah proses pembangunan ekonomi yang dilakukan baik di tingkat nasional maupun regional (daerah) (De Fretes, 2017). Pertumbuhan ekonomi tidak hanya mencakup peningkatan dalam produksi barang dan jasa, tetapi juga melibatkan peningkatan dalam tingkat pendapatan, perusahaan, lapangan pekerjaan, dan standar hidup masyarakat.</p>
<p>Provinsi Papua merupakan daerah yang memiliki wilayah paling luas dibandingkan dengan provinsi lain di Indonesia. Secara geografis, posisi wilayah Papua sangat strategis, yaitu berada di jalur pelayaran Asia Tenggara dan Pasifik. Provinsi Papua memiliki potensi ekonomi yang besar, terutama dalam sektor pertambangan yang melibatkan sumber daya alam seperti tambang emas, tembaga, dan gas alam. Salah satu indikator untuk mengetahui kondisi ekonomi suatu daerah dalam suatu periode tertentu ditunjukkan oleh Produk Domestik Regional Bruto (PDRB). Sektor pertambangan dan penggalian di Papua telah menjadi penyumbang signifikan terhadap PDRB regional. Pertumbuhan ekonomi yang berkelanjutan sangat bergantung pada sektor ini. Salah satu perusahaan pertambangan yang berkontribusi besar dalam mewujudkan pertumbuhan ekonomi pesat di Papua adalah PT Freeport Indonesia (PTFI).</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini membahas mengenai pengaruh kontribusi sektor pertambangan dan penggalian terhadap pertumbuhan ekonomi di Provinsi Papua. Dalam penelitian ini, penulis mengambil objek penelitian dari Badan Pusat Statistik (BPS) Provinsi Papua. Ruang lingkup penelitian ini melibatkan 2 variabel utama yakni kontribusi sektor pertambangan pada Produk Domestik Regional Bruto (PDRB) Provinsi Papua dan pertumbuhan ekonomi Provinsi Papua. Data yang digunakan merupakan data yang bersifat <em>time series</em> yaitu dalam kurun waktu 2012-2021 yang disajikan dalam bentuk persentase (%).</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Apakah kontribusi sektor pertambangan dan penggalian berpengaruh terhadap pertumbuhan ekonomi Provinsi Papua?</li>
<li>Bagaimana pengaruh kontribusi sektor pertambangan dan penggalian terhadap pertumbuhan ekonomi di Provinsi Papua?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Sesuai dengan rumusan masalah yang telah dipaparkan di atas, maka tujuan dilakukannya penelitian ini adalah untuk mengetahui pengaruh kontribusi sektor pertambangan dan penggalian terhadap pertumbuhan ekonomi di Provinsi Papua selama periode 2012-2021.</p>
<p>Adapun manfaat dari penelitian ini, diantaranya sebagai berikut :</p>
<ol type="1">
<li><p>Manfaat Teoritis</p>
<p>Hasil penelitian diharapkan dapat menambah wawasan yang dapat meningkatkan pengetahuan bagi pembaca mengenai dinamika ekonomi regional.</p></li>
<li><p>Manfaat Praktis</p>
<p>a. Bagi penulis</p>
<p>Penelitian ini diharapkan dapat meningkatkan pemahaman mengenai pengaruh sektor pertambangan dan penggalian terhadap pertumbuhan ekonomi di Provinsi Papua, dan mengembangkan keterampilan analisis serta metodologi penelitian.</p>
<p>b. Bagi instansi terkait</p>
<p>Penelitian ini diharapkan dapat berguna untuk meningkatkan kebijakan ekonomi dan pengelolaan sumber daya alam yang lebih efektif dan berkelanjutan di Provinsi Papua.</p></li>
</ol>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan untuk mendukung regresi univariat dalam penelitian ini meliputi :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li><p>Sektor Pertambangan dan Penggalian Provinsi Papua</p>
<p>Provinsi Papua memang kaya akan potensi sumber daya tambang, termasuk minyak dan gas bumi, emas, tembaga, batubara, nikel, pasir besi, dan sejenisnya. Potensi emas dan tembaga melibatkan sebagian besar wilayah Papua. Sebagian dari potensi ini telah dieksploitasi oleh PT Freeport Indonesia di wilayah Grasberg Tembagapura, Mimika. Sektor pertambangan dan penggalian memiliki peran penting sebagai penopang perekonomian Provinsi Papua, dan menjadi salah satu kontributor utama terhadap Produk Domestik Regional Bruto (PDRB) di wilayah&nbsp;tersebut.</p></li>
<li><p>Pertumbuhan Ekonomi</p>
<p>Pertumbuhan ekonomi mengacu pada peningkatan nilai ekonomi suatu negara atau wilayah dalam suatu periode waktu tertentu. Pertumbuhan ekonomi suatu wilayah pada umumnya diukur dengan persentase perubahan dari satu periode ke periode berikutnya dalam indikator yang disebut Produk Domestik Regional Bruto (PDRB). Menurut Sadono Sukirno, PDRB adalah nilai tambah yang dihasilkan oleh berbagai sektor ekonomi dalam suatu wilayah tertentu. Sadono Sukirno juga mengatakan bahwa PDRB dapat digunakan untuk mengukur produktivitas setiap sektor ekonomi.</p></li>
</ol>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Berikut merupakan data yang digunakan sebagai objek penelitian. Data yang digunakan meliputi data kontribusi sektor pertambangan dan penggalian pada PDRB dan data pertumbuhan ekonomi Provinsi Papua yang disajikan dalam bentuk persentase (%).</p>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 55%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Tahun</th>
<th style="text-align: center;">Kontribusi (%) Sektor Pertambangan dan Penggalian pada PDRB (X)</th>
<th style="text-align: center;">Pertumbuhan Ekonomi (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">2012</td>
<td style="text-align: center;">41.32</td>
<td style="text-align: center;">1.72</td>
</tr>
<tr class="even">
<td style="text-align: center;">2013</td>
<td style="text-align: center;">39.28</td>
<td style="text-align: center;">8.21</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2014</td>
<td style="text-align: center;">34.56</td>
<td style="text-align: center;">3.65</td>
</tr>
<tr class="even">
<td style="text-align: center;">2015</td>
<td style="text-align: center;">32.22</td>
<td style="text-align: center;">7.35</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2016</td>
<td style="text-align: center;">34.08</td>
<td style="text-align: center;">9.14</td>
</tr>
<tr class="even">
<td style="text-align: center;">2017</td>
<td style="text-align: center;">35.19</td>
<td style="text-align: center;">4.64</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2018</td>
<td style="text-align: center;">36.64</td>
<td style="text-align: center;">7.32</td>
</tr>
<tr class="even">
<td style="text-align: center;">2019</td>
<td style="text-align: center;">23.56</td>
<td style="text-align: center;">-15.74</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2020</td>
<td style="text-align: center;">28.23</td>
<td style="text-align: center;">2.39</td>
</tr>
<tr class="even">
<td style="text-align: center;">2021</td>
<td style="text-align: center;">36.84</td>
<td style="text-align: center;">15.11</td>
</tr>
</tbody>
</table>
<p>Penelitian ini menggunakan data yang bersifat <em>time series</em> yaitu dalam kurun waktu 2012-2021 yang diperoleh dari Badan Pusat Statistik (BPS) Provinsi Papua.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">'D:/Metopel_2023/Desti UAS metopel'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Kontribusi pada PDRB dan Pertumbuhan Ekonomi Papua.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"Kontribusi Sektor Pertambangan dan Penggalian pada PDRB"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap Kontribusi Sektor Pertambangan dan Penggalian pada PDRB</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>u<span class="ot">&lt;-</span><span class="fu">resid</span>(reg1)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>Y,dat<span class="sc">$</span>u,<span class="at">xlab=</span><span class="st">"Pertumbuhan Ekonomi"</span>,<span class="at">ylab=</span><span class="st">"error"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Plot pengaruh error terhadap Pertumbuhan Ekonomi</p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen yaitu kontribusi sektor pertambangan dan penggalian pada PDRB dan 1 variabel dependen yaitu pertumbuhan ekonomi. Tujuan dari penelitian ini adalah untuk mengidentifiksi hubungan antara kontribusi sektor pertambangan dan penggalian (X) dengan pertumbuhan ekonomi (Y).</p>
<p><span class="math display">\[
y=\beta_0 + \beta_1 x_t+\mu_t
\]</span></p>
<p>Di mana <span class="math inline">\(y_t\)</span> adalah Y dan <span class="math inline">\(x_t\)</span> adalah X. Di mana Y adalah pertumbuhan ekonomi Provinsi Papua, dan X adalah kontribusi sektor pertambangan dan penggalian pada PDRB Provinsi Papua.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Coefficient</th>
<th style="text-align: center;">Std.Error</th>
<th style="text-align: center;">t-value</th>
<th style="text-align: center;">Prob(.)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Intercept</td>
<td style="text-align: center;">-31.5273</td>
<td style="text-align: center;">13.9640</td>
<td style="text-align: center;">-2.258</td>
<td style="text-align: center;">0.0539</td>
</tr>
<tr class="even">
<td style="text-align: left;">X</td>
<td style="text-align: center;">1.0501</td>
<td style="text-align: center;">0.4042</td>
<td style="text-align: center;">2.598</td>
<td style="text-align: center;">0.0317</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R squared</td>
<td style="text-align: center;">0.4576</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Adjusted R-Squared</td>
<td style="text-align: center;">0.3898</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">F-Statistic</td>
<td style="text-align: center;">6.749</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Prob (F-Statistic)</td>
<td style="text-align: center;">0.03172</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Hasil regresi yang diperoleh dimasukkan ke dalam persamaan rumus, sehingga rumusnya menjadi :</p>
<p><span class="math display">\[
Y = (-31.5273) + 1.0501X
\]</span></p>
<p>Kontribusi sektor pertambangan dan penggalian berpengaruh secara positif pada pertumbuhan ekonomi Provinsi Papua, dilihat dari variabel X yang positif. Jika diasumsikan setiap kenaikan kontribusi sektor pertambangan dan penggalian pada PDRB sebesar 1%, maka pertumbuhan ekonomi akan meningkat sebesar 1.0501%. Tetapi jika kontribusi sektor pertambangan dan penggalian pada PDRB = 0, maka pertumbuhan ekonomi akan menurun&nbsp;sebesar&nbsp;31.5273%.</p>
<p>Nilai Adjusted R-Squared 0.3989 menunjukkan bahwa sebesar 39.89% variabel dependen dapat dijelaskan oleh model regresi. Nilai F-Statistic yang tinggi yaitu sebesar 6.749 dan nilai p-value yang rendah yaitu sebesar 0.0317 menunjukkan bahwa model secara keseluruhan memiliki kecenderungan untuk signifikan. Nilai p-value yang rendah pada variabel X juga menunjukkan bahwa variabel tersebut memiliki pengaruh yang signifikan terhadap variabel Y. Maka dapat disimpulkan bahwa kontribusi sektor pertambangan dan penggalian berpengaruh secara signifikan terhadap pertumbuhan ekonomi di Provinsi Papua.</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Kontribusi pada PDRB dan Pertumbuhan Ekonomi Papua.xlsx'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X,<span class="at">data=</span>dat)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X, data = dat)

Residuals:
     Min       1Q   Median       3Q      Max 
-10.1444  -1.4129  -0.2084   4.7269   7.9502 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) -31.5273    13.9640  -2.258   0.0539 .
X             1.0501     0.4042   2.598   0.0317 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.305 on 8 degrees of freedom
Multiple R-squared:  0.4576,    Adjusted R-squared:  0.3898 
F-statistic: 6.749 on 1 and 8 DF,  p-value: 0.03172</code></pre>
</div>
</div>
<p>Jika setiap kenaikan kontribusi sektor pertambangan dan penggalian pada PDRB diasumsikan sebesar 1%, maka pertumbuhan ekonomi akan meningkat sebesar 1.0501%. Tetapi jika kontribusi sektor pertambangan dan penggalian pada PDRB = 0, maka pertumbuhan ekonomi akan menurun sebesar 31.5273%.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan hasil penelitian, dapat disimpulkan bahwa sektor pertambangan dan penggalian berpengaruh terhadap pertumbuhan ekonomi di Provinsi Papua. Hasil analisis menunjukkan bahwa setiap kenaikan kontribusi sektor pertambangan dan penggalian pada Produk Domestik Regional Bruto (PDRB) sebesar 1% memberikan dampak positif terhadap pertumbuhan ekonomi, karena berpotensi meningkatkan pertumbuhan ekonomi sebesar 1.0501%. Namun, jika kontribusi sektor tersebut pada PDRB mencapai nol, akan berdampak negatif terhadap pertumbuhan ekonomi, karena mengakibatkan penurunan sebesar 31.5273%. Dengan demikian, perencanaan dan pengelolaan sektor pertambangan dan penggalian perlu diperhatikan untuk mendukung pembangunan ekonomi yang berkelanjutan dan stabil di Provinsi Papua.</p>
</section>
<section id="saran" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="saran"><span class="header-section-number">6</span> Saran</h2>
<p>Untuk hasil penelitian yang lebih akurat, disarankan untuk menambahkan variabel yang relevan dengan variabel utama yang diteliti.</p>
</section>
<section id="referensi" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="referensi"><span class="header-section-number">7</span> Referensi</h2>
<p>De Fretes, P. N. (2017). ANALISIS SEKTOR UNGGULAN (LQ),STRUKTUR EKONOMI (SHIFT SHARE), DAN PROYEKSI PRODUK DOMESTIK REGIONAL BRUTO PROVINSI PAPUA 2018. <em>Develop</em>, <em>1</em>(2). https://doi.org/10.25139/dev.v1i2.384</p>
<p>Media, K. C. (2022, September 11). Pertumbuhan Ekonomi: Pengertian, Ciri, dan Faktor yang Mempengaruhinya. KOMPAS.com. <a href="https://money.kompas.com/read/2022/01/08/080854626/pertumbuhan-ekonomi-pengertian-ciri-dan-faktor-yang-mempengaruhinya" class="uri">https://money.kompas.com/read/2022/01/08/080854626/pertumbuhan-ekonomi-pengertian-ciri-dan-faktor-yang-mempengaruhinya</a></p>
<p>Kompas.id. (2021, February 3). Provinsi Papua: Wilayah Kaya Sumber Daya Alam di Ujung Timur Indonesia. Kompas.id. <a href="https://www.kompas.id/baca/daerah/2021/02/03/provinsi-papua" class="uri">https://www.kompas.id/baca/daerah/2021/02/03/provinsi-papua</a></p>
<p>Menurut.id. (n.d). Pengertian PDRB Menurut Sadono Sukirno. Menurut.id <a href="https://www.menurut.id/pengertian-pdrb-menurut-sadono-sukirno" class="uri">https://www.menurut.id/pengertian-pdrb-menurut-sadono-sukirno</a></p>
<p>Badan Pusat Statistik Provinsi Papua. (2016, November 30). <em>Laporan Perekonomian Daerah Provinsi Papua Tahun 2015</em>. Retrieved January 8, 2024, from <a href="https://papua.beta.bps.go.id/id/publication/2016/11/30/add2c74db1e0b7703ca6d8e4/laporan-perekonomian-daerah-provinsi-papua-tahun-2015.html" class="uri">https://papua.beta.bps.go.id/id/publication/2016/11/30/add2c74db1e0b7703ca6d8e4/laporan-perekonomian-daerah-provinsi-papua-tahun-2015.html</a></p>
<p>Badan Pusat Statistik Provinsi Papua. (2019, December 6). <em>Laporan Perekonomian Daerah Provinsi Papua 2019</em>. Retrieved January 8, 2024, from <a href="https://papua.beta.bps.go.id/id/publication/2019/12/06/4c9ea38b6d220b85c6ba1b9f/laporan-perekonomian-daerah-provinsi-papua-2019.html" class="uri">https://papua.beta.bps.go.id/id/publication/2019/12/06/4c9ea38b6d220b85c6ba1b9f/laporan-perekonomian-daerah-provinsi-papua-2019.html</a></p>
<p>Badan Pusat Statistik Provinsi Papua. (2022, December 20). <em>Laporan Perekonomian Daerah Provinsi Papua 2022</em>. Retrieved January 8, 2024, from <a href="https://papua.beta.bps.go.id/id/publication/2022/12/20/b1f9a7861f9ed943695abfca/laporan-perekonomian-daerah-provinsi-papua-2022.html" class="uri">https://papua.beta.bps.go.id/id/publication/2022/12/20/b1f9a7861f9ed943695abfca/laporan-perekonomian-daerah-provinsi-papua-2022.html</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>